---
title: "Big Data"
subtitle: ""
date: "today"
author: "Diego Saavedra García"
lang: "es"
format:
  revealjs:
    #chalkboard: 
      #buttons: false
    #toc: true
    incremental: false
    slide-number: true
    preview-links: auto
    logo: img/logo_uide.png
    #css: styles.css
    footer: <https://www.uide.edu.ec>
    theme: dark
    makeindex: true
    #multiplex: true
    transition: fade
    chalkboard: true #Pizarra
    auto-stretch: false
    smaller: false
    scrollable: true
    presentation-title-slide-text-alig: left
    presentation-slide-text-align: justify
    #menu: true
  #html: 
    #code-fold: true
    #html-math-method: katex
    #multiplex: true
    #transition: fade
    #auto-stretch: false
editor: visual
execute: 
  echo: true
    
bibliography: Bibliografia.bib
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl"
editor_options: 
  chunk_output_type: console
---

## Generalidades.

El **Big Data** es una área dentro de la Inteligencia Artificial, Dentro de la misma encontramos grandes cantidades de datos estructurados y datos no estructurados. Esta semana conoceremos acerca de este gran mundo.

## Agenda.

## Analice este Ejemplo.

+-------------+-------------+-------------+-------------+-------------+
|             |             |             |             |             |
+=============+=============+=============+=============+=============+
+-------------+-------------+-------------+-------------+-------------+

## Glosario de Términos.

-   Datos Estructurados.

-   Datos no Estructurados.

-   On premise (on prem).

-   Cloud Computing

    -   AWS (Amazon).

    -   Azure (Microsoft)

-   Data Warehouse.

-   Machine Learning.

-   Big Data

## Big Data.

Definición:

Según @marinescu2023 dentro del mundo del Big Data existen algunas características del Big Data son las 3 "V".

1.  Volumen.
2.  Velocidad y
3.  Variedad.

El **volumen** se explica por si mismo, la **velocidad** significa que las respuestas a las consultas y a las solicitudes de análisis de datos tienen que ser muy rápidas. La **variedad** reconoce la amplia gama de fuentes y formatos de datos. La persistencia significa que los datos tienen un valor duradero.

El Big Data abarca un amplio espectro de datos que incluyen contenidos generados por los usuarios y datos generados por máquinas. Algunos de los datos están muy estructurados, como en el caso de los historiales de los pacientes en la atención sanitaria, las reclamaciones de seguros o los documentos hipotecarios. Otros son datos brutos procedentes de sensores, archivos de registro o datos generados por las redes sociales.

## ETL

-   **E**xtracción.

-   **T**ransformación.

-   **L**oad.

## Ciclo de Vida de los Datos.

-   Captura (ingesta).

-   Almacenamiento.

-   Procesamiento y análisis.

-   Exploración y visualización.

## Bibliografía
